import pandas as pd
import numpy as np

locations = [
    "Hulimavu Lake",
    "Arekere Lake",
    "Sarakki Lake",
    "Puttenahalli Lake",
    "Ibblur Lake",
    "Mangammana Palya Lake",
    "Kodige Singasandra Lake",
    "Singasandra Lake",
    "Agara Lake",
    "Somasundra Palya Lake",
    "Garveybhavipalya Lake",
    "Basavanapura Lake",
    "Gottigere Lake",
    "Subbarayana Lake",
    "Kalena Agrahara Lake STP",
    "Chikkammanahalli Lake",
    "Kammanahalli Lake",
    "Yelenahalli Lake",
    "Nyanappanahalli Lake",
    "Kothanuru Lake",
    "Konanakunte Lake",
    "Chunchaghatta Kere",
    "Swarnakunte Gudda Kere",
    "Subedarana Kere",
    "Basapura Lake - 1",
    "Basapura Lake - 2",
    "Begur Lake",
    "Chikka Begur Lake",
    "Parappana Agrahara lake",
    "Konappana Agrahara Lake",
    "Kudlu Doddakere",
    "Kudlu Chikka Kere STP",
    "Chowdeshwari layout Lake",
    "Annappanakere",
    "Vasantpura Lake",
    "Kalyanikunte lake",
    "Devarakere Lake",
    "Dorekere Lake",
    "Subramanyapura Lake",
    "Uttarahalli Lake",
    "Gubbalalu Lake",
    "Doddakallsandra Lake",
    "Kembattahalli lake",
    "Anjanapura lake",
    "Doddabidarakallu Lake",
    "Lakshmipura Lake",
    "Abbigere Lake",
    "Mallasandra Gudde Lake",
    "Shivapura Lake",
    "Nelagadarenahalli Lake",
    "Bagalaguntte Lake",
    "Kamagondanahalli Lake",
    "Dasarahalli Lake",
    "Kariobanahalli Lake",
    "Kaggadasapura Lake",
    "Kelagina Byrasandra Lake",
    "Kacharakanahalli Lake",
    "Ulsoor lake",
    "Chikkabasavanapura Lake",
    "Mahadevapura Lake-1",
    "Vijanapura kere",
    "Sigehalli Lake",
    "Devsandra kere",
    "Challakere Lake",
    "Kalkere Lake",
    "Vibhuthipura kere",
    "Junnasandra lake",
    "Benniganahalli Lake",
    "Gunjur mouji kere",
    "Hormavu Agara Lake",
    "Rampura kere",
    "Nagareshwara-Nagenahalli Lake",
    "Gangashetty Lake",
    "Horamavu Lake",
    "Vengaiahna kere",
    "Pattandur agrahara lake-124",
    "Mahadevapura Lake-2",
    "Pattandur agrahara-54 Lake",
    "B. Narayanapura Lake",
    "Chikkabellandur Lake",
    "Bhattarahalli Lake",
    "Kowdenahalli lake",
    "Sitaram Palya lake",
    "Ambalipura Kelagina kere",
    "Nalluralli tank",
    "Gunjur Palya kere",
    "Hoodi kere",
    "Gunjuru Karmelaram lake",
    "Panathur lake-2",
    "Panathur lake-1",
    "Jimkenahalli Lake/ Varanasi Lake",
    "Hoodi Giddanakere Lake",
    "Amblipura melina kere",
    "Kaigondanahalli Lake",
    "Kasavanahalli lake",
    "Bhoganahalli Lake",
    "Haraluru kere",
    "Sadaramangala Lake",
    "Sowl kere",
    "Devarabeesanahalli Lake",
    "Doddanekundi lake",
    "Doddakanenahalli kere",
    "Garudachar Palya (Goshala) Lake",
    "Munnekolalu kere",
    "Garudachar Palya Lake",
    "Chinnappanahalli lake",
    "Shilavanthana kere",
    "Siddapura Lake",
    "Kundalahalli Lake",
    "Kengeri Lake",
    "Busegowdana lake",
    "Mylasandra lake",
    "Dubasipalay lake",
    "Mangammanahalli lake",
    "Gandhinagar Hosakere",
    "Varahasandra Lake",
    "Chikkabasthi lake",
    "Chikkagowdanapaly lake",
    "Konasandra Lake",
    "Lingadeeranahalli-13 Lake",
    "Talghatapura Lake",
    "Bayyapanapalya Kunte Lake",
    "H Gollahalli kere",
    "Ullala lake",
    "Jogi kere",
    "Handrahalli kere",
    "Lingadeeranahalli (handrahalli)",
    "Herohalli Lake",
    "Gattigerepalya (Sompura) lake",
    "Sompura Lake",
    "Vishwaneedum Lake",
    "Hosakerehalli lake",
    "Srigandadakaval lake",
    "Pattanagere/ Kenchenhalli lake",
    "Mallathahalli lake",
    "J.P Park Lake",
    "Halage vaderahalli Lake",
    "Nagarabhavi Lake",
    "Bhimana Kuppe kere",
    "Kenchanapura lake",
    "Kodigehalli lake",
    "Bheemana Katte kere",
    "Kannali Lake",
    "Soolikere",
    "Kempambudhi Lake",
    "Byrasandra Lake",
    "Mesthripalya Lake",
    "Deepanjali Lake",
    "Gowdanapalya Lake",
    "Yediyur Lake",
    "Sankey Lake",
    "Nayandahalli Lake",
    "Srinivasapura Lake",
    "Singapura Lake",
    "Bellahalli Lake",
    "Doddabommasandra Lake",
    "Narasipura Lake-1",
    "Narasipura Lake-2",
    "Rachenahalli Lake",
    "Amruthahalli Lake",
    "Venkateshpura Lake",
    "Jakkur Lake",
    "Agrahara Lake",
    "Chokkanahalli Lake",
    "Thirumenahalli Lake",
    "Kogilu Lake",
    "Palanahalli Lake",
    "Kattigenahalli Lake",
    "Bettahalli lake",
    "Shivanahalli Lake",
    "Allalasandra Lake",
    "Medi Agrahara Lake",
    "Vaderahalli lake",
    "Yalahanka Lake",
    "Harohalli Lake",
    "Avalahalli Lake",
    "Ramagondanahalli Lake",
    "Veerasagara Lake",
    "Attur Lake"
]
num_rows = len(locations)
# Shuffle locations to avoid any pattern
np.random.shuffle(locations)

# Generate data
data = {
    "Serial Number": np.arange(1, num_rows+1),
    "STN Code": np.random.choice(range(1000, 9999), size=num_rows, replace=False),
    "Location": locations[:num_rows],
    "Dissolved O2": np.round(np.random.uniform(0, 10, num_rows), 2),
    "pH": np.round(np.random.uniform(6, 9, num_rows), 2),
    "Conductivity": np.round(np.random.uniform(300, 3000, num_rows), 2),
    "BOD": np.random.randint(2, 51, num_rows),
    "Fluorides Level": np.round(np.random.uniform(0, 1.5, num_rows), 2),
    "Boron Level": np.round(np.random.uniform(0, 2, num_rows), 2),
    "Calcium Level": np.round(np.random.uniform(0, 100, num_rows), 2),
    "Phosphate Level": np.round(np.random.uniform(0, 5, num_rows), 2),
    "Sodium Level": np.round(np.random.uniform(0, 200, num_rows), 2),
    "Ammonium Level": np.round(np.random.uniform(0, 1, num_rows), 2),
    "Carbonate Level": np.round(np.random.uniform(0, 2, num_rows), 2),
    "Bicarbonate Level": np.round(np.random.uniform(0, 10, num_rows), 2),
    "COD": np.round(np.random.uniform(0, 150, num_rows), 2),
    "Turbidity": np.round(np.random.uniform(0, 200, num_rows), 2),
    "Useful":np.round(np.random.uniform(100,1000,num_rows),2),
    "Cleaning Required": np.zeros(num_rows, dtype=int)
}

# Create DataFrame

df = pd.DataFrame(data)

# Save to CSV
file_path = "synthetic_water_quality_data_bengaluru.csv"
df.to_csv(file_path, index=False)

